### ISSUE TITLE
autoload.php config

### ISSUE THREAD

**Issue by asadw1** [michaelsoriano/user-registration-codeigniter#1]
Hi! I'm following your tutorial on this, and the part that says: 

> Let’s autoload the following items in config > autoload.php: libraries > ‘session’, helper > ‘url’, ‘form’, ‘security’.

Is not very clear. Can you explain what exactly needs to be changed inside autoload.php? Mine looks like this right now (unchanged):

```
/*
| -------------------------------------------------------------------
|  Auto-load Libraries
| -------------------------------------------------------------------
| These are the classes located in system/libraries/ or your
| application/libraries/ directory, with the addition of the
| 'database' library, which is somewhat of a special case.
|
| Prototype:
|
|	$autoload['libraries'] = array('database', 'email', 'session');
|
| You can also supply an alternative library name to be assigned
| in the controller:
|
|	$autoload['libraries'] = array('user_agent' => 'ua');
*/
$autoload['libraries'] = array();
```

**Comment by michaelsoriano** [comment]
Try this:

$autoload['libraries'] = array('session');
$autoload['helpers'] = array('url', 'form', 'security');

**Comment by asadw1** [comment]
Thanks, this works!

**Comment by abedputra** [comment]
$autoload['helper'] = array('url', 'form', 'security');
$autoload['helper']  -> without 's'
