### ISSUE TITLE
The login was unsucessful

### ISSUE THREAD

**Issue by Asyasyarif** [michaelsoriano/user-registration-codeigniter#7]
i try your app then it show error "**The login was unsucessful**", any idea how to fix this ?

**Comment by michaelsoriano** [comment]
did you go through the whole registration process?

**Comment by Asyasyarif** [comment]
ya, i'm successful register, when i'm go to login.  can't login.
im try your project first. (cloning)

**Comment by michaelsoriano** [comment]
check your database - there is a a user? With password etc ?

**Comment by Asyasyarif** [comment]
yes, im already check it ... the password already available.
btw im using Xampp v3.2.2 & PHP 7.2.4, its no problem ?

**Comment by michaelsoriano** [comment]
Give me some time to look at it and get back to you

**Comment by michaelsoriano** [comment]
I updated the password.php file for the hashing logic. This may have something to do with it. Note that I updated the codebase to include the entire CI code.
